version: '3.8'

services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=restaurant-finder
    networks:
      - app-network
    restart: unless-stopped

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/restaurant-finder
      - REQUEST_DELAY_MS=2000
      - MAX_RETRIES=5
      - CONCURRENT_REQUESTS=2
      - COORDINATES_FILE=/app/coords.csv
    volumes:
      - ./data:/app/data
      - ./coords.csv:/app/coords.csv
    networks:
      - app-network
    restart: on-failure

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/restaurant-finder
      - PORT=4000
    ports:
      - "4000:4000"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 